import React, { useState } from 'react';
import { 
  Sparkles, 
  AlertTriangle, 
  ShieldAlert, 
  ShieldCheck, 
  CheckCircle2, 
  Clock, 
  DollarSign, 
  FileText, 
  ArrowRight, 
  Copy, 
  Check, 
  Download, 
  Printer, 
  UploadCloud, 
  HelpCircle,
  ExternalLink
} from 'lucide-react';
import { SimplifiedDocumentResult, SupportedLanguage, ReadingLevel } from '../types';
import { SAMPLE_CONTRACTS, SampleContract } from '../data/sampleContracts';
import { safeFetchJson } from '../lib/api';

interface SimplifyDocViewProps {
  documentText: string;
  setDocumentText: (text: string) => void;
  language: SupportedLanguage;
  readingLevel: ReadingLevel;
  onSelectClauseToClarify: (clause: string) => void;
  result: SimplifiedDocumentResult | null;
  setResult: (res: SimplifiedDocumentResult | null) => void;
  isLoading: boolean;
  setIsLoading: (loading: boolean) => void;
  error: string | null;
  setError: (err: string | null) => void;
}

export const SimplifyDocView: React.FC<SimplifyDocViewProps> = ({
  documentText,
  setDocumentText,
  language,
  readingLevel,
  onSelectClauseToClarify,
  result,
  setResult,
  isLoading,
  setIsLoading,
  error,
  setError,
}) => {
  const [copied, setCopied] = useState(false);
  const [activePreset, setActivePreset] = useState<string>('freelance-contractor');
  const [expandedClauseIndex, setExpandedClauseIndex] = useState<number | null>(0);

  const handleAnalyze = async () => {
    if (!documentText.trim()) {
      setError('Please provide or select a legal document to analyze.');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const data = await safeFetchJson<SimplifiedDocumentResult>('/api/simplify-legal-doc', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          documentText,
          readingLevel,
          language,
        }),
      });

      setResult(data);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'An unexpected error occurred while contacting the AI service.');
    } finally {
      setIsLoading(false);
    }
  };

  const loadPreset = (presetId: string) => {
    const contract = SAMPLE_CONTRACTS.find((c) => c.id === presetId);
    if (contract) {
      setActivePreset(presetId);
      setDocumentText(contract.text);
      setResult(null);
      setError(null);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Error case (a): Empty file
    if (file.size === 0) {
      setError('Upload Error: The selected file is completely empty (0 bytes). Please upload a valid contract.');
      return;
    }

    // Error case (b): Corrupted or non-text format
    const validExtensions = ['.txt', '.md', '.json', '.rtf'];
    const hasValidExt = validExtensions.some((ext) => file.name.toLowerCase().endsWith(ext));
    if (!file.type.startsWith('text/') && !hasValidExt) {
      setError('Upload Notice: For fast local in-browser inspection, please upload plain text (.txt, .md) or paste your contract text directly into the box.');
      return;
    }

    const reader = new FileReader();
    reader.onerror = () => {
      setError('Failed to read file. The file may be corrupted or inaccessible.');
    };
    reader.onload = (event) => {
      const content = event.target?.result as string;
      if (!content || !content.trim()) {
        setError('Upload Error: The file content is empty or unreadable.');
        return;
      }
      setDocumentText(content);
      setActivePreset('');
      setResult(null);
      setError(null);
    };
    reader.readAsText(file);
  };

  const handleCopySummary = () => {
    if (!result) return;
    const textToCopy = `LEGALASSIST AI ANALYSIS REPORT
Document Type: ${result.documentType}
Risk Score: ${result.riskScore}/100 (${result.riskLevel})
Summary: ${result.executiveSummary}
Verdict: ${result.overallVerdict}

RED FLAGS:
${result.redFlags.map((rf) => `- [${rf.severity}] ${rf.title}: ${rf.plainExplanation}`).join('\n')}
`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadReport = () => {
    if (!result) return;
    const report = `# Legal Analysis Report: ${result.documentType}
Generated by LegalAssist AI for PromptWars Legal Access Challenge

## Overall Verdict
**Risk Score:** ${result.riskScore}/100 (${result.riskLevel})
**Recommendation:** ${result.overallVerdict}

## Executive Summary
${result.executiveSummary}

## Critical Red Flags & Traps
${result.redFlags
  .map(
    (rf) => `### ⚠️ ${rf.title} (${rf.severity} Severity)
> "${rf.clauseSnippet}"
**Plain Explanation:** ${rf.plainExplanation}
**Action to Take:** ${rf.recommendedAction}
`
  )
  .join('\n')}

## Clause-by-Clause Translation
${result.simplifiedClauses
  .map(
    (sc) => `### ${sc.sectionName} [${sc.riskRating}]
- **Original:** "${sc.originalTextSnippet}"
- **Plain Language:** ${sc.plainLanguageMeaning}
- **Hidden Gotchas:** ${sc.gotchas}
`
  )
  .join('\n')}

## Key Obligations
${result.keyObligations.map((ko) => `- **${ko.party}:** ${ko.obligation} *(Due: ${ko.timelineOrTrigger})*`).join('\n')}

## Financial & Termination Provisions
- **Payment Terms:** ${result.financialAndTerminationTerms.paymentTerms}
- **Termination Conditions:** ${result.financialAndTerminationTerms.terminationConditions}
- **Renewal / Auto-Renew:** ${result.financialAndTerminationTerms.renewalTerms}

---
*Disclaimer: Generated for educational and informational purposes; verify with licensed legal counsel.*`;

    const blob = new Blob([report], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `LegalAssist-Report-${result.documentType.replace(/\s+/g, '_')}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const getRiskColor = (score: number) => {
    if (score < 30) return { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', bar: 'bg-emerald-500' };
    if (score < 60) return { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200', bar: 'bg-amber-500' };
    if (score < 80) return { bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200', bar: 'bg-orange-500' };
    return { bg: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200', bar: 'bg-rose-600' };
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Intro Header */}
      <div className="bg-white border border-stone-200 rounded-2xl p-6 shadow-xs">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
          <div className="space-y-1">
            <h2 className="text-xl font-bold text-stone-900 font-serif flex items-center gap-2">
              <FileText className="w-5 h-5 text-amber-600" />
              Demystify & Simplify Any Legal Document
            </h2>
            <p className="text-sm text-stone-600 max-w-3xl">
              Contracts are purposefully written with archaic legalese and trap doors. Paste any agreement, lease, NDA, or terms of service to extract a plain-English translation, risk score, key obligations, and hidden liabilities.
            </p>
          </div>

          {/* Quick Presets for Challenge Evaluators */}
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs font-semibold text-stone-500 uppercase tracking-wider">
              Quick Test:
            </span>
            {SAMPLE_CONTRACTS.map((sample) => (
              <button
                key={sample.id}
                onClick={() => loadPreset(sample.id)}
                className={`text-xs px-2.5 py-1.5 rounded-lg border font-medium transition-all ${
                  activePreset === sample.id
                    ? 'bg-amber-50 border-amber-300 text-amber-900 shadow-xs'
                    : 'bg-stone-50 border-stone-200 text-stone-700 hover:bg-stone-100'
                }`}
                title={sample.description}
              >
                {sample.title.split('(')[0]}
              </button>
            ))}
          </div>
        </div>

        {/* Input Area */}
        <div className="mt-5 space-y-3">
          <div className="relative">
            <textarea
              id="legal-document-input"
              value={documentText}
              onChange={(e) => {
                setDocumentText(e.target.value);
                setActivePreset('');
              }}
              rows={8}
              placeholder="Paste contract text here, or select a sample agreement above..."
              className="w-full rounded-xl border border-stone-300 p-4 font-mono text-xs sm:text-sm text-stone-800 focus:border-amber-500 focus:ring-2 focus:ring-amber-500/20 focus:outline-none transition-all resize-y leading-relaxed bg-stone-50/50"
            />
            <div className="absolute bottom-3 right-3 flex items-center gap-3 text-xs text-stone-400 bg-white/90 px-2 py-1 rounded border border-stone-200 backdrop-blur">
              <span>{documentText.split(/\s+/).filter(Boolean).length} words</span>
              <span>•</span>
              <span>{documentText.length} chars</span>
            </div>
          </div>

          {/* Controls Bar */}
          <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
            <div className="flex items-center gap-2">
              <label
                htmlFor="file-upload"
                className="cursor-pointer inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-stone-300 bg-white text-xs font-medium text-stone-700 hover:bg-stone-50 transition-colors shadow-xs"
              >
                <UploadCloud className="w-3.5 h-3.5 text-stone-500" />
                Upload .txt / .md
                <input
                  id="file-upload"
                  type="file"
                  accept=".txt,.md,.text"
                  onChange={handleFileUpload}
                  className="hidden"
                />
              </label>

              {documentText && (
                <button
                  onClick={() => {
                    setDocumentText('');
                    setResult(null);
                    setError(null);
                  }}
                  className="text-xs text-stone-500 hover:text-stone-700 px-2 py-1"
                >
                  Clear text
                </button>
              )}
            </div>

            <button
              id="analyze-doc-btn"
              onClick={handleAnalyze}
              disabled={isLoading || !documentText.trim()}
              className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-stone-900 text-white hover:bg-stone-800 disabled:opacity-50 disabled:cursor-not-allowed font-medium text-sm transition-all shadow-sm hover:shadow active:scale-[0.99] cursor-pointer"
            >
              {isLoading ? (
                <>
                  <Sparkles className="w-4 h-4 animate-spin text-amber-400" />
                  Analyzing with Gemini 3.1 Flash...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-amber-400" />
                  Simplify & Scan Document
                </>
              )}
            </button>
          </div>
        </div>

        {error && (
          <div className="mt-4 p-4 bg-rose-50 border border-rose-200 rounded-xl text-xs sm:text-sm text-rose-800 flex items-start gap-2.5">
            <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold">Analysis Notice</p>
              <p>{error}</p>
            </div>
          </div>
        )}
      </div>

      {/* Prominent On-Screen GenAI Loading Indicator (Live Processing) */}
      {isLoading && (
        <div className="bg-white border-2 border-amber-400/80 rounded-2xl p-8 sm:p-10 text-center space-y-4 shadow-md">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-100 text-amber-900 text-xs font-bold uppercase tracking-wider">
            <span className="w-2 h-2 rounded-full bg-amber-500 animate-ping" />
            Live GenAI in Action
          </div>
          <div className="w-14 h-14 rounded-2xl bg-stone-900 flex items-center justify-center mx-auto text-amber-400 shadow-sm">
            <Sparkles className="w-7 h-7 animate-spin text-amber-400" />
          </div>
          <div className="space-y-2 max-w-lg mx-auto">
            <h3 className="text-lg font-bold text-stone-900 font-serif">
              AI is analyzing your document in real-time...
            </h3>
            <p className="text-xs text-stone-600 leading-relaxed">
              <strong>Engine:</strong> Google Gemini 3.1 Flash Lite (<code className="font-mono text-amber-700">@google/genai</code> official SDK). Parsing clauses, detecting trapdoors, scoring risk from 0–100, and translating into <strong>{language}</strong> ({readingLevel} mode).
            </p>
          </div>
          <div className="max-w-xs mx-auto bg-stone-100 rounded-full h-1.5 overflow-hidden">
            <div className="bg-amber-500 h-full w-2/3 animate-pulse" />
          </div>
        </div>
      )}

      {/* Analysis Results View */}
      {result && !isLoading && (
        <div className="space-y-6">
          {/* Top Scorecard & Verdict */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Risk Gauge Card */}
            <div className="bg-white border border-stone-200 rounded-2xl p-6 shadow-xs flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-stone-400">
                    Risk Assessment
                  </span>
                  <span
                    className={`text-xs px-2.5 py-0.5 rounded-full font-bold border ${getRiskColor(result.riskScore).bg} ${getRiskColor(result.riskScore).text} ${getRiskColor(result.riskScore).border}`}
                  >
                    {result.riskLevel} Risk
                  </span>
                </div>

                <div className="mt-4 flex items-baseline gap-2">
                  <span className="text-4xl sm:text-5xl font-extrabold text-stone-900 tracking-tight">
                    {result.riskScore}
                  </span>
                  <span className="text-sm text-stone-400 font-medium">/ 100</span>
                </div>

                {/* Progress bar */}
                <div className="w-full bg-stone-100 rounded-full h-2.5 mt-3 overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all duration-700 ${getRiskColor(result.riskScore).bar}`}
                    style={{ width: `${Math.min(100, Math.max(5, result.riskScore))}%` }}
                  />
                </div>

                <p className="mt-4 text-xs text-stone-600 leading-relaxed">
                  {result.riskSummary}
                </p>
              </div>

              <div className="mt-5 pt-4 border-t border-stone-100 flex items-center justify-between text-xs text-stone-500">
                <span>Document: <strong>{result.documentType}</strong></span>
                <span>Language: <strong>{language}</strong></span>
              </div>
            </div>

            {/* Executive TL;DR & Verdict */}
            <div className="lg:col-span-2 bg-white border border-stone-200 rounded-2xl p-6 shadow-xs flex flex-col justify-between">
              <div className="space-y-4">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-stone-400">
                    Plain-Language Summary (TL;DR)
                  </span>

                  <div className="flex items-center gap-1">
                    <button
                      onClick={handleCopySummary}
                      className="inline-flex items-center gap-1 text-xs px-2.5 py-1 text-stone-600 hover:text-stone-900 hover:bg-stone-100 rounded border border-stone-200 transition-colors"
                      title="Copy plain summary"
                    >
                      {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      {copied ? 'Copied' : 'Copy'}
                    </button>
                    <button
                      onClick={handleDownloadReport}
                      className="inline-flex items-center gap-1 text-xs px-2.5 py-1 text-stone-600 hover:text-stone-900 hover:bg-stone-100 rounded border border-stone-200 transition-colors"
                      title="Download Markdown Report"
                    >
                      <Download className="w-3.5 h-3.5" />
                      Export .MD
                    </button>
                  </div>
                </div>

                <p className="text-base text-stone-800 leading-relaxed font-normal">
                  {result.executiveSummary}
                </p>

                {/* Overall Verdict Banner */}
                <div className="p-4 rounded-xl bg-amber-50/80 border border-amber-200/80 flex items-start gap-3">
                  <ShieldAlert className="w-5 h-5 text-amber-700 shrink-0 mt-0.5" />
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-amber-900">
                      Counsel Verdict & Action Recommendation
                    </h4>
                    <p className="text-xs sm:text-sm text-amber-900/90 mt-0.5 font-medium leading-normal">
                      {result.overallVerdict}
                    </p>
                  </div>
                </div>
              </div>

              {/* Identified Parties */}
              {result.keyParties && result.keyParties.length > 0 && (
                <div className="mt-4 pt-3 border-t border-stone-100 flex flex-wrap gap-2 text-xs">
                  <span className="text-stone-400 font-medium">Parties:</span>
                  {result.keyParties.map((p, idx) => (
                    <span
                      key={idx}
                      className="bg-stone-100 text-stone-700 px-2 py-0.5 rounded font-medium"
                    >
                      {p.role}: <strong>{p.name}</strong>
                    </span>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Critical Red Flags & Traps */}
          {result.redFlags && result.redFlags.length > 0 && (
            <div className="bg-white border border-stone-200 rounded-2xl p-6 shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-7 h-7 rounded-lg bg-rose-100 text-rose-700 flex items-center justify-center">
                    <AlertTriangle className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="text-base font-bold text-stone-900 font-serif">
                      Critical Red Flags & Hidden Traps ({result.redFlags.length})
                    </h3>
                    <p className="text-xs text-stone-500">
                      Clauses with severe legal exposure, one-sided liabilities, or unexpected restrictions
                    </p>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {result.redFlags.map((flag, idx) => (
                  <div
                    key={idx}
                    className="border border-stone-200 rounded-xl p-4 bg-stone-50/50 hover:bg-stone-50 transition-colors flex flex-col justify-between space-y-3"
                  >
                    <div className="space-y-2">
                      <div className="flex items-center justify-between gap-2">
                        <h4 className="text-sm font-bold text-stone-900 flex items-center gap-1.5">
                          <span className="w-2 h-2 rounded-full bg-rose-500 shrink-0" />
                          {flag.title}
                        </h4>
                        <span
                          className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded ${
                            flag.severity === 'Critical'
                              ? 'bg-rose-100 text-rose-800'
                              : flag.severity === 'High'
                              ? 'bg-orange-100 text-orange-800'
                              : 'bg-amber-100 text-amber-800'
                          }`}
                        >
                          {flag.severity}
                        </span>
                      </div>

                      <blockquote className="text-xs font-mono text-stone-600 bg-white p-2.5 rounded border border-stone-200 italic line-clamp-3">
                        "{flag.clauseSnippet}"
                      </blockquote>

                      <p className="text-xs text-stone-700 leading-relaxed">
                        <strong className="text-stone-900">Plain Explanation:</strong> {flag.plainExplanation}
                      </p>
                    </div>

                    <div className="pt-2 border-t border-stone-200/70 flex items-center justify-between gap-2">
                      <div className="text-xs text-emerald-800 bg-emerald-50 px-2.5 py-1 rounded font-medium border border-emerald-200/60 flex-1">
                        <strong>Counter Action:</strong> {flag.recommendedAction}
                      </div>

                      <button
                        onClick={() => onSelectClauseToClarify(flag.clauseSnippet)}
                        className="text-xs text-amber-700 hover:text-amber-900 font-semibold inline-flex items-center gap-1 px-2 py-1 rounded hover:bg-amber-50 transition-colors shrink-0"
                        title="Open in Clause Clarifier & Redline Generator"
                      >
                        Redline
                        <ArrowRight className="w-3 h-3" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Clause-by-Clause Translation */}
          {result.simplifiedClauses && result.simplifiedClauses.length > 0 && (
            <div className="bg-white border border-stone-200 rounded-2xl p-6 shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-base font-bold text-stone-900 font-serif">
                    Clause-by-Clause Translation ({result.simplifiedClauses.length} Sections)
                  </h3>
                  <p className="text-xs text-stone-500">
                    Side-by-side breakdown of the original legalese against straightforward everyday meaning
                  </p>
                </div>
              </div>

              <div className="space-y-3">
                {result.simplifiedClauses.map((clause, idx) => {
                  const isExpanded = expandedClauseIndex === idx;
                  return (
                    <div
                      key={idx}
                      className="border border-stone-200 rounded-xl overflow-hidden transition-all bg-white"
                    >
                      <button
                        onClick={() => setExpandedClauseIndex(isExpanded ? null : idx)}
                        className="w-full text-left px-4 py-3 bg-stone-50/60 hover:bg-stone-50 flex items-center justify-between gap-3 border-b border-transparent transition-colors"
                      >
                        <div className="flex items-center gap-2.5">
                          <span
                            className={`w-2.5 h-2.5 rounded-full shrink-0 ${
                              clause.riskRating === 'Hazardous'
                                ? 'bg-rose-500'
                                : clause.riskRating === 'Caution'
                                ? 'bg-amber-500'
                                : 'bg-emerald-500'
                            }`}
                          />
                          <span className="text-sm font-bold text-stone-900">
                            {clause.sectionName}
                          </span>
                          <span
                            className={`text-[10px] px-2 py-0.5 rounded font-semibold ${
                              clause.riskRating === 'Hazardous'
                                ? 'bg-rose-50 text-rose-700 border border-rose-200'
                                : clause.riskRating === 'Caution'
                                ? 'bg-amber-50 text-amber-700 border border-amber-200'
                                : 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                            }`}
                          >
                            {clause.riskRating}
                          </span>
                        </div>

                        <span className="text-xs text-stone-500 font-medium">
                          {isExpanded ? 'Collapse' : 'Expand'}
                        </span>
                      </button>

                      {isExpanded && (
                        <div className="p-4 space-y-3 border-t border-stone-100 bg-white">
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {/* Original */}
                            <div className="space-y-1">
                              <span className="text-[11px] font-bold text-stone-400 uppercase tracking-wider">
                                Original Legalese:
                              </span>
                              <div className="text-xs font-mono text-stone-700 bg-stone-50 p-3 rounded-lg border border-stone-200 leading-relaxed">
                                "{clause.originalTextSnippet}"
                              </div>
                            </div>

                            {/* Plain Meaning */}
                            <div className="space-y-1">
                              <span className="text-[11px] font-bold text-emerald-700 uppercase tracking-wider">
                                What It Actually Means For You:
                              </span>
                              <div className="text-xs text-stone-900 bg-emerald-50/50 p-3 rounded-lg border border-emerald-100 leading-relaxed font-medium">
                                {clause.plainLanguageMeaning}
                              </div>
                            </div>
                          </div>

                          {clause.gotchas && (
                            <div className="text-xs text-amber-800 bg-amber-50/60 p-2.5 rounded-lg border border-amber-200/60 flex items-start gap-2">
                              <AlertTriangle className="w-3.5 h-3.5 text-amber-600 shrink-0 mt-0.5" />
                              <div>
                                <strong>Gotcha / Surprise:</strong> {clause.gotchas}
                              </div>
                            </div>
                          )}

                          <div className="flex justify-end pt-1">
                            <button
                              onClick={() => onSelectClauseToClarify(clause.originalTextSnippet)}
                              className="text-xs text-stone-700 hover:text-stone-950 font-semibold inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-stone-200 hover:bg-stone-50 transition-colors shadow-xs"
                            >
                              Clarify & Generate Redline Script
                              <ArrowRight className="w-3.5 h-3.5 text-amber-600" />
                            </button>
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Key Obligations & Financial Rules */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Key Obligations */}
            {result.keyObligations && result.keyObligations.length > 0 && (
              <div className="bg-white border border-stone-200 rounded-2xl p-6 shadow-xs space-y-3">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                  <h3 className="text-base font-bold text-stone-900 font-serif">
                    Key Obligations & Duties
                  </h3>
                </div>

                <div className="space-y-2.5">
                  {result.keyObligations.map((ob, idx) => (
                    <div
                      key={idx}
                      className="p-3 rounded-xl border border-stone-200 bg-stone-50/50 text-xs space-y-1"
                    >
                      <div className="flex items-center justify-between text-stone-800 font-bold">
                        <span>{ob.party}</span>
                        <span className="text-[11px] font-normal text-stone-500 flex items-center gap-1">
                          <Clock className="w-3 h-3 text-stone-400" />
                          {ob.timelineOrTrigger}
                        </span>
                      </div>
                      <p className="text-stone-600 leading-normal">{ob.obligation}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Financial & Termination Terms */}
            {result.financialAndTerminationTerms && (
              <div className="bg-white border border-stone-200 rounded-2xl p-6 shadow-xs space-y-3">
                <div className="flex items-center gap-2">
                  <DollarSign className="w-5 h-5 text-amber-600" />
                  <h3 className="text-base font-bold text-stone-900 font-serif">
                    Financial & Exit Provisions
                  </h3>
                </div>

                <div className="space-y-3 text-xs">
                  <div className="p-3 rounded-xl border border-stone-200 bg-stone-50/50 space-y-1">
                    <span className="font-bold text-stone-900 block">
                      Payment & Fee Schedule:
                    </span>
                    <p className="text-stone-600 leading-relaxed">
                      {result.financialAndTerminationTerms.paymentTerms}
                    </p>
                  </div>

                  <div className="p-3 rounded-xl border border-stone-200 bg-stone-50/50 space-y-1">
                    <span className="font-bold text-stone-900 block">
                      Termination & Exit Rights:
                    </span>
                    <p className="text-stone-600 leading-relaxed">
                      {result.financialAndTerminationTerms.terminationConditions}
                    </p>
                  </div>

                  <div className="p-3 rounded-xl border border-stone-200 bg-stone-50/50 space-y-1">
                    <span className="font-bold text-stone-900 block">
                      Renewal & Auto-Renew Provisions:
                    </span>
                    <p className="text-stone-600 leading-relaxed">
                      {result.financialAndTerminationTerms.renewalTerms}
                    </p>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
